trigger:
- master

resources: 
  repositories:
    - repository: exampleAppRepo
      type: github
      endpoint: facuxfdz
      name: facuxfdz/response-time-app-infra
pool:
  vmImage: ubuntu-latest

jobs:
  - job: build_app 
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhub

    - bash: |
        short_hash=`git rev-parse --short=7 HEAD`
        echo "##vso[task.setvariable variable=SHORT_HASH]$short_hash"
      displayName: Export git short hash

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: facuxfdz/example-app
        tags: $(SHORT_HASH)

    - bash: |
        git config --global user.email "facuassain@gmail.com"
        git config --global user.name "azure-pipeline"
      displayName: Git config
  - job: averga
    dependsOn: build_app
    steps:
      - checkout: exampleAppRepo
      - script: |
          cat deployment.yaml | docker run -i --rm mikefarah/yq e ".spec.template.spec.containers[0].image"
        displayName: Update deployment yaml
        workingDirectory: $(Build.SourcesDirectory)/dev