trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: holis
    jobs:
      - job: jobmy

        steps:

        # - task: Docker@2
        #   displayName: Login to Docker Hub
        #   inputs:
        #     command: login
        #     containerRegistry: dockerhub

        - bash: |
            boka="facu"
            echo "##vso[task.setvariable variable=one]$boka"
          displayName: Export git short hash

        - bash: echo $(one)

        # - task: Docker@2
        #   displayName: Build and Push
        #   inputs:
        #     command: buildAndPush
        #     repository: example-app
        #     tags: $(SHORT_HASH)