trigger:
- master

resources: 
  repositories:
    - repository: exampleAppRepo
      type: github
      endpoint: facuxfdz
      name: facuxfdz/response-time-app-infra
      ref: master
pool:
  vmImage: ubuntu-latest

jobs:
  - job: build_app 
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerhub

    - bash: |
        short_hash=`git rev-parse --short=7 HEAD`
        echo "##vso[task.setvariable variable=SHORT_HASH;isoutput=true]$short_hash"
      name: passOutput

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: facuxfdz/example-app
        tags: $(passOutput.SHORT_HASH)

  - job: averga
    dependsOn: build_app
    variables: 
      SHORT_HASH: $[ dependencies.build_app.outputs['passOutput.SHORT_HASH'] ]
    steps:
      - bash: |
          git config --global user.email "facuassain@gmail.com"
          git config --global user.name "azure-pipeline"
        displayName: Git config
      - checkout: exampleAppRepo
      - script: |
          short_hash=$(SHORT_HASH)
          git checkout -b master
          cat dev/deployment.yaml | docker run -i --rm mikefarah/yq e ".spec.template.spec.containers[0].image = \"facuxfdz/example-app:$short_hash\"" > dev/deployment.yaml
          git add .
          git commit -m "Pipeline commit" -m "Deployment image updated"
          git branch
          echo "lpmss"
          git push -u origin master
        displayName: Update deployment yaml
        workingDirectory: $(Build.SourcesDirectory)/
